import arrow from "/assets/icons/arrow.png";
import boldArrow from "/assets/icons/boldArrow.webp";
import animatedAsterisk from "/assets/icons/animateAsterisk.svg";

import about1 from "/assets/images/about1.webp";
import about2 from "/assets/images/about2.webp";
import highlight1 from "/assets/images/highlight1.webp";
import highlight2 from "/assets/images/highlight2.webp";
import highlight4 from "/assets/images/highlight4.webp";
import aboutram from "/assets/images/aboutRam.webp";
import creative1 from "/assets/images/creative1.webp";
import creative2 from "/assets/images/creative2.webp";
import creative3 from "/assets/images/creative3.webp";
import creative4 from "/assets/images/creative4.webp";
import creative5 from "/assets/images/creative5.webp";
import creative6 from "/assets/images/creative6.webp";
import portrait1 from "/assets/images/portrait1.webp";
import portrait2 from "/assets/images/portrait2.webp";
import portrait3 from "/assets/images/portrait3.webp";
import portrait4 from "/assets/images/portrait4.webp";
import portrait5 from "/assets/images/portrait5.webp";
import portrait6 from "/assets/images/portrait6.webp";
import runway1 from "/assets/images/runway1.webp";
import runway2 from "/assets/images/runway2.webp";
import featuredmain1 from "/assets/images/featuredmain1.webp";
import featuredleft1 from "/assets/images/featuredleft1.webp";
import featuredleft2 from "/assets/images/featuredleft2.webp";
import featuredmain2 from "/assets/images/featuredmain2.webp";
import featuredright1 from "/assets/images/featuredright1.webp";
import featuredright2 from "/assets/images/featuredright2.webp";
import lips1 from "/assets/images/lips1.webp";
import lips2 from "/assets/images/lips2.webp";
import aboutAdImg from "/assets/images/aboutAd.webp";
import heroPlace from "/assets/images/heroPlaceholder.webp";
import aboutVidPlace from '/assets/images/aboutVidPlaceholder.webp';
import about1ImagePlace from '/assets/images/about1placeholder.webp';
import about2ImagePlace from "/assets/images/about2placeholder.webp";
import workedWithPlace from "/assets/images/workedWithPlaceholder.webp";
import highlight1Place from "/assets/images/highlight1Placeholder.webp";
import highlight2Place from "/assets/images/highlight2Placeholder.webp";
import highlight3Place from "/assets/images/highlight4Placeholder.webp";
import runway1Place from "/assets/images/runway1Placeholder.webp";
import runway2Place from "/assets/images/runway2Placeholder.webp";
import selectedWorksPlace from "/assets/images/selectedWorksPlaceholder.webp";
import creativePlaceholder1 from "/assets/images/creative1Placeholder.webp";
import creativePlaceholder2 from "/assets/images/creative2Placeholder.webp";
import creativePlaceholder3 from "/assets/images/creative3Placeholder.webp";
import creativePlaceholder4 from "/assets/images/creative4Placeholder.webp";
import creativePlaceholder5 from "/assets/images/creative5Placeholder.webp";
import creativePlaceholder6 from "/assets/images/creative6Placeholder.webp";
import portraitPlaceholder1 from "/assets/images/portrait1Placeholder.webp";
import portraitPlaceholder2 from "/assets/images/portrait2Placeholder.webp";
import portraitPlaceholder3 from "/assets/images/portrait3Placeholder.webp";
import portraitPlaceholder4 from "/assets/images/portrait4Placeholder.webp";
import portraitPlaceholder5 from "/assets/images/portrait5Placeholder.webp";
import portraitPlaceholder6 from "/assets/images/portrait6Placeholder.webp";
import featuredLeftPlaceholder1 from "/assets/images/featuredleft1Placeholder.webp";
import featuredLeftPlaceholder2 from "/assets/images/featuredleft2Placeholder.webp";
import featuredRightPlaceholder1 from "/assets/images/featuredright1Placeholder.webp";
import featuredRightPlaceholder2 from "/assets/images/featuredright2Placeholder.webp";
import featuredMainPlaceholder1 from "/assets/images/featuredmain1Placeholder.webp";
import featuredMainPlaceholder2 from "/assets/images/featuredmain2Placeholder.webp";
import lips1Placeholder from "/assets/images/lips1Placeholder.webp";
import lips2Placeholder from "/assets/images/lips2Placeholder.webp";
import aboutRamPlaceholder from "/assets/images/aboutRamPlaceholder.webp";
import aboutAdPlaceholder from "/assets/images/aboutAdPlaceholder.webp";

import aboutvideo from "/assets/videos/aboutvideo.mp4";
import workedWith from "/assets/videos/workedWith.mp4";
import workVideo from "/assets/videos/workVideo.mp4";
import aboutAd from "/assets/videos/aboutAd.mp4";
import aboutAd4 from "/assets/videos/aboutAd5.mp4";
import heroVideo from "/assets/videos/mainVid.mp4";

import lips from "../assets/animations/lips.json";
import scroll from "../assets/animations/scroll.json";
import aboutramscroll from "../assets/animations/aboutramscroll.json";

export const scrollArrow = arrow;
export const boldArrowImg = boldArrow;
export const animateAsteriskSvg = animatedAsterisk;

export const aboutImage1 = about1;
export const aboutImage2 = about2;
export const highlightImage1 = highlight1;
export const highlightImage2 = highlight2;
export const highlightImage4 = highlight4;
export const aboutRam = aboutram;
export const creativeImage1 = creative1;
export const creativeImage2 = creative2;
export const creativeImage3 = creative3;
export const creativeImage4 = creative4;
export const creativeImage5 = creative5;
export const creativeImage6 = creative6;
export const portraitImage1 = portrait1;
export const portraitImage2 = portrait2;
export const portraitImage3 = portrait3;
export const portraitImage4 = portrait4;
export const portraitImage5 = portrait5;
export const portraitImage6 = portrait6;
export const runwayImage1 = runway1;
export const runwayImage2 = runway2;
export const featuredMain1 = featuredmain1;
export const featuredLeft1 = featuredleft1;
export const featuredLeft2 = featuredleft2;
export const featuredMain2 = featuredmain2;
export const featuredRight1 = featuredright1;
export const featuredRight2 = featuredright2;
export const lipsMain1 = lips1;
export const lipsMain2 = lips2;
export const aboutAdImage = aboutAdImg;
export const heroPlaceImg = heroPlace;
export const aboutVidPlaceImg = aboutVidPlace;
export const about1ImagePlaceholder = about1ImagePlace;
export const about2ImagePlaceholder = about2ImagePlace;
export const workedWithPlaceholderImage = workedWithPlace;
export const highlightPlaceholderImage1 = highlight1Place;
export const highlightPlaceholderImage2 = highlight2Place;
export const highlightPlaceholderImage3 = highlight3Place;
export const runway1PlaceholderImage = runway1Place;
export const runway2PlaceholderImage = runway2Place;
export const selectedWorksPlaceholderImage = selectedWorksPlace;
export const creativePlaceholder1Img = creativePlaceholder1;
export const creativePlaceholder2Img = creativePlaceholder2;
export const creativePlaceholder3Img = creativePlaceholder3;
export const creativePlaceholder4Img = creativePlaceholder4;
export const creativePlaceholder5Img = creativePlaceholder5;
export const creativePlaceholder6Img = creativePlaceholder6;
export const portrait1PlaceholderImg = portraitPlaceholder1;
export const portrait2PlaceholderImg = portraitPlaceholder2;
export const portrait3PlaceholderImg = portraitPlaceholder3;
export const portrait4PlaceholderImg = portraitPlaceholder4;
export const portrait5PlaceholderImg = portraitPlaceholder5;
export const portrait6PlaceholderImg = portraitPlaceholder6;
export const featuredLeftPlaceholder1Img = featuredLeftPlaceholder1;
export const featuredLeftPlaceholder2Img = featuredLeftPlaceholder2;
export const featuredRightPlaceholder1Img = featuredRightPlaceholder1;
export const featuredRightPlaceholder2Img = featuredRightPlaceholder2;
export const featuredMainPlaceholder1Img = featuredMainPlaceholder1;
export const featuredMainPlaceholder2Img = featuredMainPlaceholder2;
export const lips1PlaceholderImg = lips1Placeholder;
export const lips2PlaceholderImg = lips2Placeholder;
export const aboutRamPlaceholderImg = aboutRamPlaceholder;
export const aboutAdPlaceholderImg = aboutAdPlaceholder;

export const aboutVideo = aboutvideo;
export const workedWithVideo = workedWith;
export const workVideoMain = workVideo;
export const aboutAdVideo = aboutAd;
export const aboutAdVideo4 = aboutAd4;
export const heroVideoMain = heroVideo;

export const Lips = lips;
export const scrollDown = scroll;
export const aboutRamScroll = aboutramscroll;
