import arrow from "/assets/icons/arrow.png";
import boldArrow from "/assets/icons/boldArrow.webp";
import animatedAsterisk from "/assets/icons/animateAsterisk.svg";

import about1 from "/assets/images/about1.webp";
import about2 from "/assets/images/about2.webp";
import highlight1 from "/assets/images/highlight1.webp";
import highlight2 from "/assets/images/highlight2.webp";
import highlight4 from "/assets/images/highlight4.webp";
import aboutram from "/assets/images/aboutRam.webp";
import creative1 from "/assets/images/creative1.webp";
import creative2 from "/assets/images/creative2.webp";
import creative3 from "/assets/images/creative3.webp";
import creative4 from "/assets/images/creative4.webp";
import creative5 from "/assets/images/creative5.webp";
import creative6 from "/assets/images/creative6.webp";
import portrait1 from "/assets/images/portrait1.webp";
import portrait2 from "/assets/images/portrait2.webp";
import portrait3 from "/assets/images/portrait3.webp";
import portrait4 from "/assets/images/portrait4.webp";
import portrait5 from "/assets/images/portrait5.webp";
import portrait6 from "/assets/images/portrait6.webp";
import runway1 from "/assets/images/runway1.webp";
import runway2 from "/assets/images/runway2.webp";
import featuredmain1 from "/assets/images/featuredmain1.webp";
import featuredleft1 from "/assets/images/featuredleft1.webp";
import featuredleft2 from "/assets/images/featuredleft2.webp";
import featuredmain2 from "/assets/images/featuredmain2.webp";
import featuredright1 from "/assets/images/featuredright1.webp";
import featuredright2 from "/assets/images/featuredright2.webp";
import lips1 from "/assets/images/lips1.webp";
import lips2 from "/assets/images/lips2.jpg";
import lips3 from "/assets/images/lips3.webp";
import lips4 from "/assets/images/lips4.webp";
import aboutAdImg from "/assets/images/aboutAd.jpg";
import heroPlace from "/assets/images/heroPlaceholder.webp";
import aboutVidPlace from '/assets/images/aboutVidPlaceholder.webp';
import about1ImagePlace from '/assets/images/about1placeholder.webp';
import about2ImagePlace from "/assets/images/about2placeholder.webp";
import workedWithPlace from "/assets/images/workedWithPlaceholder.webp";

import aboutvideo from "/assets/videos/aboutvideo.mp4";
import workedWith from "/assets/videos/workedWith.mp4";
import workVideo from "/assets/videos/workVideo.mp4";
import lipsToDieVid from "/assets/videos/lipsToDieVid.mp4";
import aboutAd from "/assets/videos/aboutAd.mp4";
import aboutAd2 from "/assets/videos/aboutAd2.mp4";
import aboutAd4 from "/assets/videos/aboutAd5.mp4";

import lips from "../assets/animations/lips.json";
import scroll from "../assets/animations/scroll.json";
import aboutramscroll from "../assets/animations/aboutramscroll.json";

export const scrollArrow = arrow;
export const boldArrowImg = boldArrow;
export const animateAsteriskSvg = animatedAsterisk;

export const aboutImage1 = about1;
export const aboutImage2 = about2;
export const highlightImage1 = highlight1;
export const highlightImage2 = highlight2;
export const highlightImage4 = highlight4;
export const aboutRam = aboutram;
export const creativeImage1 = creative1;
export const creativeImage2 = creative2;
export const creativeImage3 = creative3;
export const creativeImage4 = creative4;
export const creativeImage5 = creative5;
export const creativeImage6 = creative6;
export const portraitImage1 = portrait1;
export const portraitImage2 = portrait2;
export const portraitImage3 = portrait3;
export const portraitImage4 = portrait4;
export const portraitImage5 = portrait5;
export const portraitImage6 = portrait6;
export const runwayImage1 = runway1;
export const runwayImage2 = runway2;
export const featuredMain1 = featuredmain1;
export const featuredLeft1 = featuredleft1;
export const featuredLeft2 = featuredleft2;
export const featuredMain2 = featuredmain2;
export const featuredRight1 = featuredright1;
export const featuredRight2 = featuredright2;
export const lipsMain1 = lips1;
export const lipsMain2 = lips2;
export const lipsMain3 = lips3;
export const lipsMain4 = lips4;
export const aboutAdImage = aboutAdImg;
export const heroPlaceImg = heroPlace;
export const aboutVidPlaceImg = aboutVidPlace;
export const about1ImagePlaceholder = about1ImagePlace;
export const about2ImagePlaceholder = about2ImagePlace;
export const workedWithPlaceholderImage = workedWithPlace;

export const aboutVideo = aboutvideo;
export const workedWithVideo = workedWith;
export const workVideoMain = workVideo;
export const lipsToDieVideo = lipsToDieVid;
export const aboutAdVideo = aboutAd;
export const aboutAdVideo2 = aboutAd2;
export const aboutAdVideo4 = aboutAd4;

export const Lips = lips;
export const scrollDown = scroll;
export const aboutRamScroll = aboutramscroll;
