/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: DianaV.Mendoza (https://sketchfab.com/DianaV.Mendoza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/makeup-cosmetics-97038c2b5b7d44b1851ba9e33fbd20d7
Title: Makeup & Cosmetics
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useDispatch, useSelector } from 'react-redux';
import { selectScrollDirection, selectScrollTop, setScrollDirection } from '../../../slices/navSlice';

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  const ref = useRef();
  const dispatch = useDispatch();

  const scrollTop = useSelector(selectScrollTop)
  const scrollDirection = useSelector(selectScrollDirection)
  const [ rotation, setRotation ] = useState(0);

  useEffect(() => {
    if (ref.current) {
      if(scrollDirection === "down"){
        ref.current.rotation.y = rotation + 0.1;
        setRotation(ref.current.rotation.y)
      } else if (scrollDirection === "up") {
        ref.current.rotation.y = rotation - 0.1;
        setRotation(ref.current.rotation.y)
      }          
    }
  }, [scrollTop])

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes.pCylinder13_Black_0.geometry} material={materials.Black} />
      <mesh geometry={nodes.pCylinder13_blinn5_0.geometry} material={materials.blinn5} />
      <mesh geometry={nodes.pCylinder13_Iron_0.geometry} material={materials.Iron} />
      <mesh geometry={nodes.pCylinder13_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder13_Wood_0.geometry} material={materials.Wood} />
      <mesh geometry={nodes.pCylinder13_Blush_0.geometry} material={materials.Blush} />
      <mesh geometry={nodes.pCylinder13_Crystal_0.geometry} material={materials.Crystal} />
    </group>
  )
}

useGLTF.preload('/scene.gltf');
